server:
  port: 8083

spring:
  application:
    name: schedule-service
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/staffsync_schedule}
    username: ${DB_USER:staffsync}
    password: ${DB_PASS:staffsync}
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://admin:admin@localhost:8761/eureka/}
